from django.db.models.signals import post_migrate
from django.dispatch import receiver
from .models import EstadoPerfil, EstadoNoticia, EstadoActividad, EstadoCertificado, EstadoPostulacion, Region, Comuna, Roles, Sexo, Parentesco

@receiver(post_migrate)
def create_default_data(sender, **kwargs):
    if sender.name == 'accounts':
        EstadoPerfil.objects.get_or_create(id_estadoperfil=1, descripcion='habilitado')
        EstadoPerfil.objects.get_or_create(id_estadoperfil=2, descripcion='inhabilitado')
        
        EstadoNoticia.objects.get_or_create(id_estadonoticia=1, descripcion='habilitada')
        EstadoNoticia.objects.get_or_create(id_estadonoticia=2, descripcion='inhabilitada')
        
        EstadoActividad.objects.get_or_create(id_estadoactividad=1, descripcion='habilitada')
        EstadoActividad.objects.get_or_create(id_estadoactividad=2, descripcion='inhabilitada')
        
        EstadoCertificado.objects.get_or_create(id_estadocertificado=1, descripcion='pendiente')
        EstadoCertificado.objects.get_or_create(id_estadocertificado=2, descripcion='emitido')
        
        EstadoPostulacion.objects.get_or_create(id_estadopostulacion=1, descripcion='pendiente')
        EstadoPostulacion.objects.get_or_create(id_estadopostulacion=2, descripcion='aprobado')
        EstadoPostulacion.objects.get_or_create(id_estadopostulacion=3, descripcion='rechazado')
        
        Region.objects.get_or_create(id_region=1, nombre_region='Arica y Parinacota')
        Region.objects.get_or_create(id_region=2, nombre_region='Tarapacá')
        Region.objects.get_or_create(id_region=3, nombre_region='Antofagasta')
        Region.objects.get_or_create(id_region=4, nombre_region='Atacama')
        Region.objects.get_or_create(id_region=5, nombre_region='Coquimbo')
        Region.objects.get_or_create(id_region=6, nombre_region='Valparaiso')
        Region.objects.get_or_create(id_region=7, nombre_region='Metropolitana')
        Region.objects.get_or_create(id_region=8, nombre_region='Libertador General Bernardo O’Higgins')
        Region.objects.get_or_create(id_region=9, nombre_region='Maule')
        Region.objects.get_or_create(id_region=10, nombre_region='Ñuble')
        Region.objects.get_or_create(id_region=11, nombre_region='Biobío')
        Region.objects.get_or_create(id_region=12, nombre_region='La Araucanía')
        Region.objects.get_or_create(id_region=13, nombre_region='Los Ríos')
        Region.objects.get_or_create(id_region=14, nombre_region='Los Lagos')
        Region.objects.get_or_create(id_region=15, nombre_region='Aysén del General Carlos Ibáñez del Campo')
        Region.objects.get_or_create(id_region=16, nombre_region='Magallanes y de la Antártica Chilena ')
        
        # Instancias de las regiones
        r_arica_parinacota = Region.objects.get(id_region=1)
        r_tarapaca = Region.objects.get(id_region=2)
        r_antofagasta = Region.objects.get(id_region=3)
        r_atacama = Region.objects.get(id_region=4)
        r_coquimbo = Region.objects.get(id_region=5)
        r_valparaiso = Region.objects.get(id_region=6)
        r_metropolitana = Region.objects.get(id_region=7)
        r_ohiggins = Region.objects.get(id_region=8)
        r_maule = Region.objects.get(id_region=9)
        r_nuble = Region.objects.get(id_region=10)
        r_biobio = Region.objects.get(id_region=11)
        r_araucania = Region.objects.get(id_region=12)
        r_rios = Region.objects.get(id_region=13)
        r_lagos = Region.objects.get(id_region=14)
        r_aysen = Region.objects.get(id_region=15)
        r_magallanes = Region.objects.get(id_region=16)
        
        Comuna.objects.get_or_create(id_comuna=1, nombre_comuna='Arica', id_region=r_arica_parinacota)
        Comuna.objects.get_or_create(id_comuna=2, nombre_comuna='Camarones', id_region=r_arica_parinacota)
        Comuna.objects.get_or_create(id_comuna=3, nombre_comuna='Putre', id_region=r_arica_parinacota)
        Comuna.objects.get_or_create(id_comuna=4, nombre_comuna='General Lagos', id_region=r_arica_parinacota)
        Comuna.objects.get_or_create(id_comuna=5, nombre_comuna='Alto Hospicio         ', id_region=r_tarapaca)
        Comuna.objects.get_or_create(id_comuna=6, nombre_comuna='Iquique', id_region=r_tarapaca)
        Comuna.objects.get_or_create(id_comuna=7, nombre_comuna='Huara', id_region=r_tarapaca)
        Comuna.objects.get_or_create(id_comuna=8, nombre_comuna='Camiña', id_region=r_tarapaca)
        Comuna.objects.get_or_create(id_comuna=9, nombre_comuna='Colchane', id_region=r_tarapaca)
        Comuna.objects.get_or_create(id_comuna=10, nombre_comuna='Pica', id_region=r_tarapaca)
        Comuna.objects.get_or_create(id_comuna=11, nombre_comuna='Pozo Almonte', id_region=r_tarapaca)
        Comuna.objects.get_or_create(id_comuna=12, nombre_comuna='Tocopilla', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=13, nombre_comuna='María Elena', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=14, nombre_comuna='Calama', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=15, nombre_comuna='Ollagüe', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=16, nombre_comuna='San Pedro de Atacama', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=17, nombre_comuna='Antofagasta', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=18, nombre_comuna='Mejillones', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=19, nombre_comuna='Sierra Gorda', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=20, nombre_comuna='Taltal', id_region=r_antofagasta)
        Comuna.objects.get_or_create(id_comuna=21, nombre_comuna='Chañaral', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=22, nombre_comuna='Diego de Almagro', id_region=r_atacama)
        Comuna.objects.get_or_create(id_comuna=23, nombre_comuna='Copiapó', id_region=r_atacama)
        Comuna.objects.get_or_create(id_comuna=24, nombre_comuna='Caldera', id_region=r_atacama)
        Comuna.objects.get_or_create(id_comuna=25, nombre_comuna='Tierra Amarilla', id_region=r_atacama)
        Comuna.objects.get_or_create(id_comuna=26, nombre_comuna='Vallenar', id_region=r_atacama)
        Comuna.objects.get_or_create(id_comuna=27, nombre_comuna='Freirina', id_region=r_atacama)
        Comuna.objects.get_or_create(id_comuna=28, nombre_comuna='Huasco', id_region=r_atacama)
        Comuna.objects.get_or_create(id_comuna=29, nombre_comuna='Alto del Carmen', id_region=r_atacama)
        Comuna.objects.get_or_create(id_comuna=30, nombre_comuna='La Serena', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=31, nombre_comuna='La Higuera', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=32, nombre_comuna='Coquimbo', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=33, nombre_comuna='Andacollo', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=34, nombre_comuna='Vicuña', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=35, nombre_comuna='Paihuano', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=36, nombre_comuna='Ovalle', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=37, nombre_comuna='Río Hurtado', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=38, nombre_comuna='Monte Patria', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=39, nombre_comuna='Combarbalá', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=40, nombre_comuna='Punitaqui', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=41, nombre_comuna='Illapel', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=42, nombre_comuna='Salamanca', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=43, nombre_comuna='Los Vilos', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=44, nombre_comuna='Canela', id_region=r_coquimbo)
        Comuna.objects.get_or_create(id_comuna=45, nombre_comuna='La Ligua', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=46, nombre_comuna='Petorca', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=47, nombre_comuna='Cabildo', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=48, nombre_comuna='Zapallar', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=49, nombre_comuna='Papudo', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=50, nombre_comuna='Los Andes', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=51, nombre_comuna='San Esteban', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=52, nombre_comuna='Calle Larga', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=53, nombre_comuna='Rinconada', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=54, nombre_comuna='San Felipe', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=55, nombre_comuna='Putaendo', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=56, nombre_comuna='Santa María', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=57, nombre_comuna='Panquehue', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=58, nombre_comuna='Llaillay', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=59, nombre_comuna='Catemu', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=60, nombre_comuna='Quillota', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=61, nombre_comuna='La Cruz', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=62, nombre_comuna='Calera', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=63, nombre_comuna='Nogales', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=64, nombre_comuna='Hijuelas', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=65, nombre_comuna='Limache', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=66, nombre_comuna='Olmué', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=67, nombre_comuna='Valparaíso', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=68, nombre_comuna='Viña del Mar', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=69, nombre_comuna='Quintero', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=70, nombre_comuna='Puchuncaví', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=71, nombre_comuna='Quilpué', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=72, nombre_comuna='Villa Alemana', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=73, nombre_comuna='Casablanca', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=74, nombre_comuna='Concón', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=75, nombre_comuna='Juan Fernández', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=76, nombre_comuna='San Antonio', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=77, nombre_comuna='Cartagena', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=78, nombre_comuna='El Tabo', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=79, nombre_comuna='El Quisco', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=80, nombre_comuna='Algarrobo', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=81, nombre_comuna='Santo Domingo', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=82, nombre_comuna='Isla de Pascua', id_region=r_valparaiso)
        Comuna.objects.get_or_create(id_comuna=83, nombre_comuna='Rancagua', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=84, nombre_comuna='Graneros', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=85, nombre_comuna='Mostazal', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=86, nombre_comuna='Codegua', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=87, nombre_comuna='Machalí', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=88, nombre_comuna='Olivar', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=89, nombre_comuna='Requinoa', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=90, nombre_comuna='Rengo', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=91, nombre_comuna='Malloa', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=92, nombre_comuna='Quinta de Tilcoco', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=93, nombre_comuna='San Vicente', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=94, nombre_comuna='Pichidegua', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=95, nombre_comuna='Peumo', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=96, nombre_comuna='Coltauco', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=97, nombre_comuna='Coinco', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=98, nombre_comuna='Doñihue', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=99, nombre_comuna='Las Cabras', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=100, nombre_comuna='San Fernando', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=101, nombre_comuna='Chimbarongo', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=102, nombre_comuna='Placilla', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=103, nombre_comuna='Nancagua', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=104, nombre_comuna='Chépica', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=105, nombre_comuna='Santa Cruz', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=106, nombre_comuna='Lolol', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=107, nombre_comuna='Pumanque', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=108, nombre_comuna='Palmilla', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=109, nombre_comuna='Peralillo', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=110, nombre_comuna='Pichilemu', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=111, nombre_comuna='Navidad', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=112, nombre_comuna='Litueche', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=113, nombre_comuna='La Estrella', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=114, nombre_comuna='Marchihue', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=115, nombre_comuna='Paredones', id_region=r_ohiggins)
        Comuna.objects.get_or_create(id_comuna=116, nombre_comuna='Curicó', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=117, nombre_comuna='Teno', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=118, nombre_comuna='Romeral', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=119, nombre_comuna='Molina', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=120, nombre_comuna='Sagrada Familia', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=121, nombre_comuna='Hualañé', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=122, nombre_comuna='Licantén', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=123, nombre_comuna='Vichuquén', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=124, nombre_comuna='Rauco', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=125, nombre_comuna='Talca', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=126, nombre_comuna='Pelarco', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=127, nombre_comuna='Río Claro', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=128, nombre_comuna='San Clemente', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=129, nombre_comuna='Maule', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=130, nombre_comuna='San Rafael', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=131, nombre_comuna='Empedrado', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=132, nombre_comuna='Pencahue', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=133, nombre_comuna='Constitución', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=134, nombre_comuna='Curepto', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=135, nombre_comuna='Linares', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=136, nombre_comuna='Yerbas Buenas', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=137, nombre_comuna='Colbún', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=138, nombre_comuna='Longaví', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=139, nombre_comuna='Parral', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=140, nombre_comuna='Retiro', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=141, nombre_comuna='Villa Alegre', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=142, nombre_comuna='San Javier', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=143, nombre_comuna='Cauquenes', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=144, nombre_comuna='Pelluhue', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=145, nombre_comuna='Chanco', id_region=r_maule)
        Comuna.objects.get_or_create(id_comuna=146, nombre_comuna='Chillán', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=147, nombre_comuna='San Carlos', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=148, nombre_comuna='Ñiquén', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=149, nombre_comuna='San Fabián', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=150, nombre_comuna='Coihueco', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=151, nombre_comuna='Pinto', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=152, nombre_comuna='San Ignacio', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=153, nombre_comuna='El Carmen', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=154, nombre_comuna='Yungay', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=155, nombre_comuna='Pemuco', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=156, nombre_comuna='Bulnes', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=157, nombre_comuna='Quillón', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=158, nombre_comuna='Ránquil', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=159, nombre_comuna='Portezuelo', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=160, nombre_comuna='Coelemu', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=161, nombre_comuna='Treguaco', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=162, nombre_comuna='Cobquecura', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=163, nombre_comuna='Quirihue', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=164, nombre_comuna='Ninhue', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=165, nombre_comuna='San Nicolás', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=166, nombre_comuna='Chillán Viejo', id_region=r_nuble)
        Comuna.objects.get_or_create(id_comuna=167, nombre_comuna='Alto Biobío', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=168, nombre_comuna='Los Angeles', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=169, nombre_comuna='Cabrero', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=170, nombre_comuna='Tucapel', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=171, nombre_comuna='Antuco', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=172, nombre_comuna='Quilleco', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=173, nombre_comuna='Santa Bárbara', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=174, nombre_comuna='Quilaco', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=175, nombre_comuna='Mulchén', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=176, nombre_comuna='Negrete', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=177, nombre_comuna='Nacimiento', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=178, nombre_comuna='Laja', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=179, nombre_comuna='San Rosendo', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=180, nombre_comuna='Yumbel', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=181, nombre_comuna='Concepción', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=182, nombre_comuna='Talcahuano', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=183, nombre_comuna='Penco', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=184, nombre_comuna='Tomé', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=185, nombre_comuna='Florida', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=186, nombre_comuna='Hualpén', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=187, nombre_comuna='Hualqui', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=188, nombre_comuna='Santa Juana', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=189, nombre_comuna='Lota', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=190, nombre_comuna='Coronel', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=191, nombre_comuna='San Pedro de la Paz', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=192, nombre_comuna='Chiguayante', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=193, nombre_comuna='Lebu', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=194, nombre_comuna='Arauco', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=195, nombre_comuna='Curanilahue', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=196, nombre_comuna='Los Alamos', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=197, nombre_comuna='Cañete', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=198, nombre_comuna='Contulmo', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=199, nombre_comuna='Tirua', id_region=r_biobio)
        Comuna.objects.get_or_create(id_comuna=200, nombre_comuna='Angol', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=201, nombre_comuna='Renaico', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=202, nombre_comuna='Collipulli', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=203, nombre_comuna='Lonquimay', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=204, nombre_comuna='Curacautín', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=205, nombre_comuna='Ercilla', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=206, nombre_comuna='Victoria', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=207, nombre_comuna='Traiguén', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=208, nombre_comuna='Lumaco', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=209, nombre_comuna='Purén', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=210, nombre_comuna='Los Sauces', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=211, nombre_comuna='Temuco', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=212, nombre_comuna='Lautaro', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=213, nombre_comuna='Perquenco', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=214, nombre_comuna='Vilcún', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=215, nombre_comuna='Cholchol', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=216, nombre_comuna='Cunco', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=217, nombre_comuna='Melipeuco', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=218, nombre_comuna='Curarrehue', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=219, nombre_comuna='Pucón', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=220, nombre_comuna='Villarrica', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=221, nombre_comuna='Freire', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=222, nombre_comuna='Pitrufquén', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=223, nombre_comuna='Gorbea', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=224, nombre_comuna='Loncoche', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=225, nombre_comuna='Toltén', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=226, nombre_comuna='Teodoro Schmidt', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=227, nombre_comuna='Saavedra', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=228, nombre_comuna='Carahue', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=229, nombre_comuna='Nueva Imperial', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=230, nombre_comuna='Galvarino', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=231, nombre_comuna='Padre las Casas', id_region=r_araucania)
        Comuna.objects.get_or_create(id_comuna=232, nombre_comuna='Valdivia', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=233, nombre_comuna='Mariquina', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=234, nombre_comuna='Lanco', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=235, nombre_comuna='Máfil', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=236, nombre_comuna='Corral', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=237, nombre_comuna='Los Lagos', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=238, nombre_comuna='Panguipulli', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=239, nombre_comuna='Paillaco', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=240, nombre_comuna='La Unión', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=241, nombre_comuna='Futrono', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=242, nombre_comuna='Río Bueno', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=243, nombre_comuna='Lago Ranco', id_region=r_rios)
        Comuna.objects.get_or_create(id_comuna=244, nombre_comuna='Osorno', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=245, nombre_comuna='San Pablo', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=246, nombre_comuna='Puyehue', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=247, nombre_comuna='Puerto Octay', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=248, nombre_comuna='Purranque', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=249, nombre_comuna='Río Negro', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=250, nombre_comuna='San Juan de la Costa', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=251, nombre_comuna='Puerto Montt', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=252, nombre_comuna='Puerto Varas', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=253, nombre_comuna='Cochamó', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=254, nombre_comuna='Calbuco', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=255, nombre_comuna='Maullín', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=256, nombre_comuna='Los Muermos', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=257, nombre_comuna='Fresia', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=258, nombre_comuna='Llanquihue', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=259, nombre_comuna='Frutillar', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=260, nombre_comuna='Castro', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=261, nombre_comuna='Ancud', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=262, nombre_comuna='Quemchi', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=263, nombre_comuna='Dalcahue', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=264, nombre_comuna='Curaco de Vélez', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=265, nombre_comuna='Quinchao', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=266, nombre_comuna='Puqueldón', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=267, nombre_comuna='Chonchi', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=268, nombre_comuna='Queilén', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=269, nombre_comuna='Quellón', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=270, nombre_comuna='Chaitén', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=271, nombre_comuna='Hualaihué', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=272, nombre_comuna='Futaleufú', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=273, nombre_comuna='Palena', id_region=r_lagos)
        Comuna.objects.get_or_create(id_comuna=274, nombre_comuna='Coyhaique', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=275, nombre_comuna='Lago Verde', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=276, nombre_comuna='Aysén', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=277, nombre_comuna='Cisnes', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=278, nombre_comuna='Guaitecas', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=279, nombre_comuna='Chile Chico', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=280, nombre_comuna='Río Ibánez', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=281, nombre_comuna='Cochrane', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=282, nombre_comuna="O'Higgins", id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=283, nombre_comuna='Tortel', id_region=r_aysen)
        Comuna.objects.get_or_create(id_comuna=284, nombre_comuna='Natales', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=285, nombre_comuna='Torres del Paine', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=286, nombre_comuna='Punta Arenas', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=287, nombre_comuna='Río Verde', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=288, nombre_comuna='Laguna Blanca', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=289, nombre_comuna='San Gregorio', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=290, nombre_comuna='Porvenir', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=291, nombre_comuna='Primavera', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=292, nombre_comuna='Timaukel', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=293, nombre_comuna='Cabo de Hornos', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=294, nombre_comuna='Antártica', id_region=r_magallanes)
        Comuna.objects.get_or_create(id_comuna=295, nombre_comuna='Santiago', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=296, nombre_comuna='Independencia', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=297, nombre_comuna='Conchalí', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=298, nombre_comuna='Huechuraba', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=299, nombre_comuna='Recoleta', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=300, nombre_comuna='Providencia', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=301, nombre_comuna='Vitacura', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=302, nombre_comuna='Lo Barnechea', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=303, nombre_comuna='Las Condes', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=304, nombre_comuna='Ñuñoa', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=305, nombre_comuna='La Reina', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=306, nombre_comuna='Macul', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=307, nombre_comuna='Peñalolén', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=308, nombre_comuna='La Florida', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=309, nombre_comuna='San Joaquín', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=310, nombre_comuna='La Granja', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=311, nombre_comuna='La Pintana', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=312, nombre_comuna='San Ramón', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=313, nombre_comuna='San Miguel', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=314, nombre_comuna='La Cisterna', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=315, nombre_comuna='El Bosque', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=316, nombre_comuna='Pedro Aguirre Cerda', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=317, nombre_comuna='Lo Espejo', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=318, nombre_comuna='Estación Central', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=319, nombre_comuna='Cerrillos', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=320, nombre_comuna='Maipú', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=321, nombre_comuna='Quinta Normal', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=322, nombre_comuna='Lo Prado', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=323, nombre_comuna='Pudahuel', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=324, nombre_comuna='Cerro Navia', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=325, nombre_comuna='Renca', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=326, nombre_comuna='Quilicura', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=327, nombre_comuna='Colina', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=328, nombre_comuna='Lampa', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=329, nombre_comuna='Tiltil', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=330, nombre_comuna='Puente Alto', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=331, nombre_comuna='San José de Maipo', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=332, nombre_comuna='Pirque', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=333, nombre_comuna='San Bernardo', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=334, nombre_comuna='Buin', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=335, nombre_comuna='Paine', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=336, nombre_comuna='Calera de Tango', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=337, nombre_comuna='Melipilla', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=338, nombre_comuna='María Pinto', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=339, nombre_comuna='Curacaví', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=340, nombre_comuna='Alhué', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=341, nombre_comuna='San Pedro', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=342, nombre_comuna='Talagante', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=343, nombre_comuna='Peñaflor', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=344, nombre_comuna='Isla de Maipo', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=345, nombre_comuna='El Monte', id_region=r_metropolitana)
        Comuna.objects.get_or_create(id_comuna=346, nombre_comuna='Padre Hurtado', id_region=r_metropolitana)


                
        
        
        Roles.objects.get_or_create(id_rol=1, descripcion='Administrador')
        Roles.objects.get_or_create(id_rol=2, descripcion='Junta Vecinos')
        Roles.objects.get_or_create(id_rol=3, descripcion='Vecino')
        
        Sexo.objects.get_or_create(id_sexo=1, descripcion='Femenino')
        Sexo.objects.get_or_create(id_sexo=2, descripcion='Masculino')
        
        Parentesco.objects.get_or_create(id_parentesco=1, descripcion='Titular')
        Parentesco.objects.get_or_create(id_parentesco=2, descripcion='Cónyuge')	
        Parentesco.objects.get_or_create(id_parentesco=3, descripcion='Conviviente')
        Parentesco.objects.get_or_create(id_parentesco=4, descripcion='Hijo')
        Parentesco.objects.get_or_create(id_parentesco=5, descripcion='Hijastro')
        Parentesco.objects.get_or_create(id_parentesco=6, descripcion='Abuelo')
        Parentesco.objects.get_or_create(id_parentesco=7, descripcion='Nieto')
        Parentesco.objects.get_or_create(id_parentesco=8, descripcion='Primo')
        Parentesco.objects.get_or_create(id_parentesco=9, descripcion='Sobrino')