# Generated by Django 5.1.2 on 2024-11-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfiles_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='fecha_incorporacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='id_comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.comuna'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.estado'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='id_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.region'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='numero_contacto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
