# Generated by Django 5.1.2 on 2024-11-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_perfiles_id_parentesco_alter_perfiles_id_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='last_name',
        ),
    ]
