# Generated by Django 5.1.2 on 2024-11-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_perfiles_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='id_region',
        ),
        migrations.AlterField(
            model_name='comuna',
            name='nombre_comuna',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
