# Generated by Django 5.1.2 on 2024-11-06 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_perfiles_id_region_alter_comuna_nombre_comuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('id_estadoactividad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCertificado',
            fields=[
                ('id_estadocertificado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoNoticia',
            fields=[
                ('id_estadonoticia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPerfil',
            fields=[
                ('id_estadoperfil', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPostulacion',
            fields=[
                ('id_estadopostulacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfiles',
            name='id_estado',
        ),
        migrations.AddField(
            model_name='perfiles',
            name='id_estadoperfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.estadoperfil'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
