# Generated by Django 5.1.2 on 2024-11-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_perfiles_id_estadoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='numero_contacto',
            field=models.CharField(default=12, max_length=11),
            preserve_default=False,
        ),
    ]
