# Generated by Django 5.1.2 on 2024-11-23 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_perfiles_numero_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id_familia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la familia o grupo (puedes usar el apellido del titular, por ejemplo)', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titular', models.OneToOneField(help_text='El titular de la familia', on_delete=django.db.models.deletion.CASCADE, related_name='familia_titular', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfiles',
            name='familia',
            field=models.ForeignKey(blank=True, help_text='Familia a la que pertenece este perfil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='accounts.familia'),
        ),
    ]
