# Generated by Django 5.1.2 on 2024-11-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_familia_perfiles_familia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoActividad',
        ),
        migrations.DeleteModel(
            name='EstadoCertificado',
        ),
        migrations.DeleteModel(
            name='EstadoNoticia',
        ),
        migrations.DeleteModel(
            name='EstadoPostulacion',
        ),
    ]
