# Generated by Django 5.1.2 on 2024-11-09 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_estadoactividad_estadocertificado_estadonoticia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCertificado',
            fields=[
                ('id_estadocertificado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoNoticia',
            fields=[
                ('id_estadonoticia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPostulacion',
            fields=[
                ('id_estadopostulacion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoActividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_termino', models.TimeField()),
                ('id_estadoactividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardjv.estadonoticia')),
            ],
        ),
        migrations.CreateModel(
            name='JuntaVecinos',
            fields=[
                ('id_juntavecino', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_integracion', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.comuna')),
                ('perfiles', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificadosResi',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_pstulante', models.CharField(max_length=120)),
                ('direccion_postulante', models.CharField(max_length=120)),
                ('fecha_emision', models.DateField()),
                ('rut_postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_estadocertificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardjv.estadocertificado')),
                ('id_juntavecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardjv.juntavecinos')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('id_estadonoticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardjv.estadonoticia')),
            ],
        ),
        migrations.CreateModel(
            name='PostulacionProyectos',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('objetivos', models.TextField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_estadopostulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardjv.estadopostulacion')),
                ('id_juntavecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardjv.juntavecinos')),
                ('rut_postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
