# Generated by Django 5.1.2 on 2024-11-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarda', '__first__'),
        ('dashboardjv', '0002_remove_estadoactividad_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadosresi',
            name='id_juntavecino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboarda.juntavecinos'),
        ),
        migrations.AlterField(
            model_name='postulacionproyectos',
            name='id_juntavecino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboarda.juntavecinos'),
        ),
        migrations.DeleteModel(
            name='JuntaVecinos',
        ),
    ]
