# Generated by Django 5.1.2 on 2024-11-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardjv', '0004_noticias_id_juntavecinos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
