# Generated by Django 5.1.2 on 2024-11-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardjv', '0005_alter_noticias_fecha_termino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificadosresi',
            old_name='nombre_pstulante',
            new_name='nombre_postulante',
        ),
    ]
