# Generated by Django 5.1.2 on 2024-11-25 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarda', '0005_juntavecinos_latitud_juntavecinos_longitud'),
        ('dashboardjv', '0006_rename_nombre_pstulante_certificadosresi_nombre_postulante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificadosresi',
            old_name='id_juntavecino',
            new_name='id_juntavecinos',
        ),
        migrations.RenameField(
            model_name='postulacionproyectos',
            old_name='id_juntavecino',
            new_name='id_juntavecinos',
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_juntavecinos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboarda.juntavecinos'),
            preserve_default=False,
        ),
    ]
