# Generated by Django 5.1.2 on 2024-11-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardjv', '0007_rename_id_juntavecino_certificadosresi_id_juntavecinos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadosresi',
            name='nota_estado',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
