# Generated by Django 5.1.2 on 2024-11-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardjv', '0008_certificadosresi_nota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadosresi',
            name='nota_estado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
