# Generated by Django 5.1.2 on 2024-11-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardjv', '0009_alter_certificadosresi_nota_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadosresi',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
    ]
