# Generated by Django 5.1.2 on 2024-11-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardjv', '0010_alter_certificadosresi_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='id_estadoactividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardjv.estadoactividad'),
        ),
    ]
