# Generated by Django 5.1.2 on 2024-12-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardjv', '0011_alter_actividad_id_estadoactividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_termino',
        ),
        migrations.AddField(
            model_name='actividad',
            name='cupos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
