# Generated by Django 5.1.2 on 2024-12-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardjv', '0013_inscripcionactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='periodo_inicio',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
        migrations.AddField(
            model_name='actividad',
            name='periodo_termino',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
    ]
