# Generated by Django 5.1.2 on 2024-11-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juntavecinos',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
