# Generated by Django 5.1.2 on 2024-11-14 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarda', '0003_alter_juntavecinos_perfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoJuntaVecinos',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='juntavecinos',
            name='id_estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dashboarda.estadojuntavecinos'),
            preserve_default=False,
        ),
    ]
