# Generated by Django 5.1.2 on 2024-11-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboarda', '0004_estadojuntavecinos_juntavecinos_id_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='juntavecinos',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='juntavecinos',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
